[package]
name = "dll_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
AMSI_Provider_with_Rust = { path = "../../AMSI_Provider_with_Rust" }
